version: "3.4"
volumes:
  cdc_demo:
services:
  postgres:
    container_name: cdc_demo_postgresql
    image: postgres:12.0-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cdc_demo_dev
    ports:
      - "5432:5432"
    volumes:
      - cdc_demo:/var/lib/postgresql/data
    logging:
      options:
        max-file: "5"
        max-size: "10m"
